{{- if .Values.valkey.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "langfuse.fullname" . }}-valkey-headless
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-valkey
      port: 6379
      targetPort: valkey
      protocol: TCP
  selector:
    {{- include "langfuse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "langfuse.fullname" . }}-valkey-primary
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-valkey
      port: 6379
      targetPort: valkey
      protocol: TCP
      nodePort: null
  selector:
    {{- include "langfuse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "langfuse.fullname" . }}-valkey
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
spec:
  replicas: 1
  serviceName: {{ include "langfuse.fullname" . }}-valkey-headless
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "langfuse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: valkey
  template:
    metadata:
      labels:
        {{- include "langfuse.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: valkey
    spec:
      serviceAccountName: {{ include "langfuse.serviceAccountName" . }}
      {{- with .Values.valkey.primary.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      containers:
        - name: valkey
          image: valkey/valkey:9-alpine
          imagePullPolicy: IfNotPresent
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - valkey-server
            - /etc/valkey/valkey.conf
          ports:
            - name: valkey
              containerPort: 6379
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/valkey
              readOnly: true
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "langfuse.fullname" . }}-valkey-config
{{- end }}

