{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "langfuse.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
{{- end }}
